### ISSUE TITLE
weekly.dongyueweb.com is not updated automatically

### ISSUE THREAD

**Issue by at15** [dyweb/weekly#175]
TODO

- [x] https://dyweb-weekly.netlify.com/ is live
- [x] redirect weekly.dongyueweb.com cc ~~@codeworm96~~ ? @ComMouse 
- [x] handle dyweb.github.io/weekly? now it is redirected to weekly.dongyueweb.com

![image](https://user-images.githubusercontent.com/5621298/70662017-49235080-1c1a-11ea-98f9-e75ed079bc68.png)

cc @gaocegege

**Comment by at15** [comment]
Can we switch to netlify? I guess that way we don't need to run jekyll manually

**Comment by gaocegege** [comment]
Sure, I think we can.

**Comment by at15** [comment]
@gaocegege https://dyweb-weekly.netlify.com/ is already taken ... I suppose it is you?

**Comment by at15** [comment]
Use the following setting and https://dyweb-weekly.netlify.com/ is up to date

![image](https://user-images.githubusercontent.com/5621298/71069822-58c8fa80-212e-11ea-9fa2-5ca82d1af64c.png)

**Comment by ComMouse** [comment]
How could the redirect be done? Using CNAME or just 301? I did not see any 301 options available for the DNS server so I guess more settings need to be done on the Netlify side.

I have just add a CNAME record for `weekly2.dongyueweb.com` and am not sure if it works. If you need any additional modification please let me know then.

**Comment by at15** [comment]
@ComMouse I think it's CNAME, let me check my netlify setup for at15.me, I was using gh then switched to netlify so the process should be same

**Comment by at15** [comment]
The main problem is the `docs` folder is no longer updated, netlify generate the updated content on the fly when there is a new version and does not push back to the origin repo.

Netlify uses CNAME unless we use its DNS for entire domain. 

```
weekly CNAME dyweb-weekly.netlify.com
```

http://weekly2.dongyueweb.com/ shows not found for me, it does point to a netlify server based on response header

**Comment by ComMouse** [comment]
@at15 That was weird. I'll have a double check if the DNS settings went wrong. I think it was the same CNAME record I added though.

**Comment by ComMouse** [comment]
I have changed the `weekly.dongyuweb.com` to the Netlify CNAME record and will wait to see if it works within 24 hrs.

**Comment by at15** [comment]
手动给豆点赞

**Comment by ComMouse** [comment]
It seems working now except the SSL certificate is in `*.netfliy.com` domain.

**Comment by at15** [comment]
@ComMouse it seems there is no good way to fix it ... though I am working on something similar to sync gh-pages w/ netlify https://github.com/xephonhq/awesome-time-series-database/issues/72

**Comment by ComMouse** [comment]
Hope [this link](https://docs.netlify.com/domains-https/https-ssl/#netlify-managed-certificates) would help

**Comment by at15** [comment]
I think we need to generate key pair using let's encrypt and upload it to netlify ...

**Comment by ComMouse** [comment]
I am not familiar with Netlify but from my experiences with GitHub pages usually resetting domain settings (like turn it off and turn if on or rename the domain name and then back) will force the service provider to regenerate ssl certificates and hopefully everything will just work with multiple tries lol

**Comment by at15** [comment]
It seems netlify domain are blocked on wechat browser, so we might just switch back to using github pages, with github action it should be easy. I'll try that when I have time

**Comment by ComMouse** [comment]
Issue Closed and Moved to #184
