### ISSUE TITLE
Weekly/72 for 2018/4/23

### ISSUE THREAD

**Issue by at15** [dyweb/weekly#21]
... 我只是说说而已 /w\

**Comment by at15** [comment]
https://github.com/360EntSecGroup-Skylar/goreporter

**Comment by gaocegege** [comment]
火星了哦

**Comment by at15** [comment]
@gaocegege 所以才需要 weekly 啊 .w.

**Comment by gaocegege** [comment]
吼啊，资词

**Comment by xplorld** [comment]
滋辞，感觉一直划水很不好意思

**Comment by JasonQSY** [comment]
资磁

**Comment by clouduan** [comment]
不明资词:yum:

**Comment by rudeigerc** [comment]
资瓷

**Comment by at15** [comment]
https://github.com/goreleaser/goreleaser looks good and we can implement similar things in ayi

**Comment by xplorld** [comment]
http://shields.io/ badge collection

**Comment by at15** [comment]
https://webassembly.studio/ support rust @codeworm96

**Comment by at15** [comment]
from 

- https://sqlite.org/whynotgit.html 里面的 xkcd 就是我用 git 的真实写照
- https://electronjs.org/blog/in-app-purchases electron 支持內购了(我们出个东岳的桌面客户端吧
- https://github.com/vuejs/vuepress 感觉 https://github.com/nuxt/nuxt.js 要少一些客户额
- https://edgedb.com/ 基于 pg 用 python 写的 object relational db, 支持 graphql 自己也有个 query language，说要开源，还没开源。

**Comment by ComMouse** [comment]
@gaocegege 鼓动一下新人投稿嘛？

**Comment by arrowrowe** [comment]
[~ soft era ~](https://github.com/soft-aesthetic/soft-era-vim)

🌸 Light pastel syntax theme for cozy, cute coding & typing. 🌱

![](https://raw.githubusercontent.com/soft-aesthetic/soft-era-vim/master/screenshot.jpg)

**Comment by LukeXuan** [comment]
点开看了emacs的版本，居然只有README

**Comment by LukeXuan** [comment]
为什么vendor会被commit进go的repo里，不是很懂golang的代码组织结构

**Comment by codeworm96** [comment]
@LukeXuan 其实 go 原来是单一 workspace 的，所有东西都一起堆在 $GOPATH/src 里各自的文件夹下，但是这样很难限定依赖的版本，然后有了 vendor 可以把依赖塞在自己底下，commit 就是为了锁依赖版本。

PS: 我是 go 黑，我也很讨厌这样。最近实习写 go 看了 How to Write Go Code 才理解了这个设计，但我还是很讨厌她。

**Comment by at15** [comment]
@codeworm96 很早就有了各种依赖的工具，社区也一直在改进。另外有个坑是，不完整的 vendor 会出错, 比如 `github.com/dyweb/ayi/venodr/github.com/dyweb/gommon` 和 `github.com/dyweb/gommon` 并不是一个库，虽然代码可能是一样的，编译会报错。写 example 的时候就会比较迷 https://github.com/at15/go.ice/blob/master/example/github/Gopkg.toml#L29-L48

我其实很喜欢 go 这样安排 workspace, 所以 `ayi git clone` 就按 go 的方式自动指定 clone destination。感觉比分好多文件夹用起来方便多了。我觉得性能要求不是特别高，code base 不是很大的项目，用 go 还是可以的。

**Comment by at15** [comment]
根本不知道 cpp 怎么写的 gopher 路过 ...

> Friends don't let friends use unions, unless they are type-safe .... Released in Abseil today: absl::variant, a C++11 compatible version of C++17's std:variant!

https://github.com/abseil/abseil-cpp/blob/master/absl/types/variant.h

**Comment by rudeigerc** [comment]
https://github.com/dawnlabs/carbon
Code screenshots for presentation

**Comment by gaocegege** [comment]
@rudeigerc That is cool

**Comment by at15** [comment]
- https://github.com/esnet/iperf iperf3: A TCP, UDP, and SCTP network bandwidth measurement tool
- https://github.com/Azure/brigade event based scripting for kubernetes
- https://github.com/Azure/kashti is a dashboard for brigade written in angular

**Comment by raspberryice** [comment]
Hi all, 
Should we use a tagging system to organize the submissions? Something like #editors, #databases, #mobile, etc. Everything else can be tucked under #misc.

**Comment by at15** [comment]
@raspberryice there was a standard so the weekly generator can parse it and generate weekly without human involved https://github.com/dyweb/mos/issues/1 , though I don't know how much @codeworm96 implemented ....

**Comment by gaocegege** [comment]
我们考虑联合周报么，比如吸引上科大，SJTUG 哪里的一起。。

**Comment by at15** [comment]
@gaocegege 是可以考虑，但是我觉得我们还是先把自己这边的摊子打理好比较好，否则没有完整的流程和工具链，只是坑挖大了，还是填不上 ... 早期还是先就我们自己吧，沟通和协作(如果有的话...)起来都方便一些。

**Comment by at15** [comment]
https://github.com/uber/queryparser uber's sql parser for analysis data warehouse systems, written in haskell cc (there should be a dyweb-fp team ...

**Comment by gaocegege** [comment]
当 codeworm96/dy-weekly-generator#1 好了之后我们可以把周报 archive 一下，如果可以的话以后不需要遵循周报生成器的数据结构来发了，这样更灵活。

找个合适的机会（比如第一期周报出来）跟 SJTUG 哪里的说一下问问要不要一起来

**Comment by at15** [comment]
@gaocegege 为什么要 archive，再开个新的 repo?  这个已经是新的了 .... 旧的见 https://github.com/dyweb/web-stuff

**Comment by gaocegege** [comment]
- [Katib: Kubernetes native 的超参数训练系统](http://gaocegege.com/Blog/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/katib)
- [Kubeflow 安利：在 Kubernetes 上进行机器学习](http://gaocegege.com/Blog/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/kubeflow)

发现了上海交通大学的一个同学写的关于大规模机器学习落地的两篇文章，感觉很不错，分享给大家，不用谢

**Comment by gaocegege** [comment]
@at15 Archive 不是说 GitHub 的 repo 的那个功能，就是说提交到我们这个 repo 的意思。。我的锅，表达错了

**Comment by gaocegege** [comment]
https://github.com/xtermjs/xterm.js

Full xterm terminal, in your browser， VS Code 就是用它做的 terminal

**Comment by gaocegege** [comment]
@raspberryice 

It is a little complicated, I think we could add the feature if we have more than 50 items per week. As you know, people hate any manual work, even a tag.

**Comment by htfy96** [comment]
兹瓷啊 不过没有明确主题的开源周报受众是谁呢？

**Comment by gaocegege** [comment]
受众是 everyone?

**Comment by htfy96** [comment]
@gaocegege 一般直接看HackerNews和Github Trends了……国内比较接近这个形式的是[开源日报](https://openingsource.org/daily/)，不过似乎也没什么人看的样子 :grin: 而且它主要都是前端、Web、编辑器相关的比较容易上手的东西

**Comment by gaocegege** [comment]
@htfy96 

嗯，我们的投稿是团队里的同学把自己看到比较有趣的项目发一下

**Comment by ComMouse** [comment]
Weekly locked. Please refer to #22.

**Comment by gaocegege** [comment]
@codeworm96 Please, the feature is urgent.

**Comment by xplorld** [comment]
idea: yc hacker news?

**Comment by gaocegege** [comment]
@at15 Could we use the weekly generator to summarize the issue?

**Comment by at15** [comment]
@gaocegege I think we can put the current in develop version into use, it may not be good enough, but we will never have something that is good enough ... just ship it @codeworm96 /w

![ship it](https://i.imgur.com/TiV6Z6T.png)
