### ISSUE TITLE
[feature] bookmarklet 支持

### ISSUE THREAD

**Issue by gaocegege** [dyweb/weekly#30]
From https://github.com/dyweb/weekly/issues/29#issuecomment-386511982

> 不如搞个bookmarklet提供给各自社团里的人，看到喜欢的网页一键提交，降低参与成本

需求：打开 GitHub 供稿还是太麻烦了

**Comment by htfy96** [comment]
我做了个bookmarklet: https://gist.github.com/htfy96/301ae2b1c477a4a644e943bbc27c9588

**Comment by gaocegege** [comment]
我先去看看这是啥。。。

**Comment by gaocegege** [comment]
真是厉害，好用。。

**Comment by gaocegege** [comment]
我在 FireFox 显示 ok 但是没看到投稿，我再研究一下。。

**Comment by htfy96** [comment]
@gaocegege 我重新escape了一下那个bookmarklet，应该firefox能用了吧

**Comment by gaocegege** [comment]
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”).
```

**Comment by gaocegege** [comment]
No matters, I will use Chrome instead.

**Comment by at15** [comment]
在 cli 里也可以做一个，我时候在 ayi 里加一个 .... /w

**Comment by gaocegege** [comment]
@htfy96 I invited you as the outside collaborator in this repository: https://github.com/dyweb/weekly/invitations

**Comment by htfy96** [comment]
@gaocegege accepted.

**Comment by gaocegege** [comment]
I think we should add the instructions into the repository, thus reopen it.
