### ISSUE TITLE
[feature] telegram channel/bot

### ISSUE THREAD

**Issue by codeworm96** [dyweb/weekly#33]

**Comment by SkyZH** [comment]
Seeing that [RSS](https://weekly.dongyueweb.com/feed.xml) is available, we can directly use IFTTT bot to post telegram message to channel if anything in RSS changes.

**Comment by gaocegege** [comment]
Good idea! We could have a try in it. While we need to solve #64

**Comment by gaocegege** [comment]
https://ifttt.com/applets/RXm2WDyZ-send-new-feed-items-to-a-telegram-chat

We can use this.

**Comment by SkyZH** [comment]
@gaocegege 
1. Add IFTTT bot into a public channel
2. Create an Applet on IFTTT

Then IFTTT will automatically deliver RSS updates to Telegram Channel. According to my experience in my past project, IFTTT looks for feed update for every 15 minutes usually. If anything fails, IFTTT will suspend the Applet for a while and notifies you on the website.

**Comment by gaocegege** [comment]
Yeah, the problem is that I do not know if we use telegram now @at15 @arrowrowe

**Comment by at15** [comment]
the tg bot is working though I forgot how @arrowrowe did this ... there is a bot that can subscribe to RSS feed as I recall ....
