### ISSUE TITLE
[bot] 自动化周报构建

### ISSUE THREAD

**Issue by gaocegege** [dyweb/weekly#48]
- 手动 close issue
- 自动去掉 label 并且新建一个 issue，打上 working label
- 自动完成构建
- 由 @gaocegege-bot 发 PR 到 repo
- 手动 merge

目前应该已经实现，试运行一段时间看看有哪些 bug

**Comment by yangwenmai** [comment]
这个机器人如何实现的？比较感兴趣 DevOps 实践。

**Comment by gaocegege** [comment]
@yangwenmai 

https://github.com/dyweb/dy-bot

**Comment by gaocegege** [comment]
因为一些 vendor 的 bug 导致不能 work

**Comment by at15** [comment]
@gaocegege vendor 包括 go.ice 么 .... /w 我下班去修

**Comment by gaocegege** [comment]
报解析的错误，我也不知道是哪里。。

**Comment by gaocegege** [comment]
Bot is working now
