### ISSUE TITLE
周报能否增加RSS订阅

### ISSUE THREAD

**Issue by Yisaer** [dyweb/weekly#64]
非常感谢周报的更新,支持RSS也许会更不错

**Comment by gaocegege** [comment]
https://weekly.dongyueweb.com/feed.xml

**Comment by at15** [comment]
@gaocegege 我 chrome 加载不出来

`Unsafe attempt to load URL https://dongyueweb.com/feed.xslt.xml from frame with URL https://weekly.dongyueweb.com/feed.xml. Domains, protocols and ports must match.`

**Comment by SkyZH** [comment]
If directly view source of `https://weekly.dongyueweb.com/feed.xml`, there's a tag `<?xml-stylesheet type="text/xml" href="https://dongyueweb.com/feed.xslt.xml"?>`, and `feed.xslt.xml` doesn't exist, which caused this error.

**Comment by SkyZH** [comment]
Maybe we can fix it by https://github.com/jekyll/jekyll-feed/pull/149 ?

**Comment by gaocegege** [comment]
I think it works now.
